#!/usr/bin/env python3
"""Prepared neutral collection on a separate headless Weston/Xwayland display.

Default/--check performs source/config checks only. --run consumes one attempt.
No game assets or settings are generated by this launcher. Use a sealed lab.
"""
import argparse
import datetime
import importlib.util
import json
import os
from pathlib import Path
import secrets
import signal
import subprocess
import sys
import time
from runtime_lab import identity, still_owned, stop_exact, validate, checked_file, run

def selected_shell(cfg):
    shell=cfg.get('private_display_shell','kiosk')
    if shell not in ('kiosk','desktop'):raise ValueError('Private display shell must be kiosk or desktop')
    return shell

def prepared_configuration(path):
    if path.name!='config.json':raise ValueError('Collector must use its sealed config.json')
    cfg=json.loads(path.read_text());validate(cfg)
    selected_shell(cfg)
    if cfg.get('idle_weapon_probe') is not True or not cfg.get('display_timing_probe'):
        raise ValueError('Prepared private display requires the neutral collector and timing probe')
    receipt=json.loads(Path(cfg['idle_preparation']['path']).read_text())
    checked_file(path.parent/'collect.py',receipt['private_wrapper_sha256'])
    return cfg


def private_environment(original, runtime, token):
    env=original.copy()
    for name in ('DISPLAY','WAYLAND_DISPLAY','XAUTHORITY','DBUS_SESSION_BUS_ADDRESS','MIR_SOCKET'):
        env.pop(name,None)
    env.update(XDG_RUNTIME_DIR=str(runtime),SS2VR_LAB_DISPLAY_ROOT=str(runtime),
               SS2VR_PRIVATE_CAPTURE_TOKEN=token,SS2VR_LAB_PRIVATE_DISPLAY='1',PYTHONDONTWRITEBYTECODE='1')
    return env


def tagged(raw, token, root):
    rows=raw.split(b'\0')
    return all([row for row in rows if row.startswith((key+'=').encode())]==[(key+'='+value).encode()]
               for key,value in (('SS2VR_PRIVATE_CAPTURE_TOKEN',token),('SS2VR_LAB_DISPLAY_ROOT',root)))


def gather(owned, token, root, exclude):
    for proc in Path('/proc').iterdir():
        if not proc.name.isdigit() or int(proc.name) in exclude:continue
        item=identity(proc.name)
        if not item:continue
        try:raw=(proc/'environ').read_bytes()
        except OSError:continue
        if tagged(raw,token,root):owned[(item['pid'],item['start'])]=item


def inside(cfg_path, output, display_only=False, prerequisite_only=False):
    # Weston executes this child only after its private display is ready. Certify
    # the exact parent incarnation and actual executed argv, not Popen's fork.
    expected=json.loads((output/'owner.json').read_text())
    parent=identity(os.getppid())
    if not parent or parent['pid']!=expected['pid'] or parent['start']!=expected['start'] or \
       [part.decode() for part in parent['argv'] if part]!=expected['argv']:
        raise RuntimeError('Private compositor parent identity differs')
    root=expected['runtime']
    private=Path(json.loads(cfg_path.read_text())['private_root']).resolve(strict=True)
    if not Path(root).resolve(strict=True).is_relative_to(private):
        raise RuntimeError('Private display runtime escapes its prepared root')
    if os.environ.get('XDG_RUNTIME_DIR')!=root or os.environ.get('SS2VR_LAB_DISPLAY_ROOT')!=root or \
       os.environ.get('WAYLAND_DISPLAY')!='ss2-vr-private' or not os.environ.get('DISPLAY','').startswith(':'):
        raise RuntimeError('Private display environment differs; no desktop fallback')
    # The runtime lab changes XDG_RUNTIME_DIR for Monado. Force X11, rather than
    # leaving a Wayland selector pointing at the old runtime directory.
    os.environ.pop('WAYLAND_DISPLAY',None)
    os.environ.pop('XAUTHORITY',None)
    check=subprocess.run(['xrandr','--current'],capture_output=True,timeout=5)
    (output/'xrandr.txt').write_bytes(check.stdout+check.stderr)
    if check.returncode:raise RuntimeError('Private display current-mode query failed')
    # Weston launches Xwayland on the first X-client connection. Query only
    # the DISPLAY supplied by the certified headless parent, then certify the
    # executed server before allowing any collector/Wine/native process.
    servers=[identity(p.name) for p in Path('/proc').iterdir() if p.name.isdigit()]
    servers=[p for p in servers if p and p['parent']==parent['pid'] and p['name']=='Xwayland'
             and os.environ['DISPLAY'].encode() in p['argv']]
    if len(servers)!=1:raise RuntimeError('Private Xwayland ownership is ambiguous')
    (output/'child.json').write_text(json.dumps({'pid':os.getpid(),'start':identity(os.getpid())['start'],
        'display':os.environ['DISPLAY'],'xwayland_pid':servers[0]['pid'],'xwayland_start':servers[0]['start'],
        'desktop_input':False},indent=2)+'\n')
    if display_only:
        (output/'collection-outcome.json').write_text(json.dumps({'completed':True,'display_only':True,
            'collector_launched':False,'game_launched':False,'data_ready_for_review':False}))
        return
    if prerequisite_only:
        cfg=prepared_configuration(cfg_path)
        if cfg.get('display_prerequisite_only') is not True:
            raise RuntimeError('Prerequisite-only operation is not sealed in this configuration')
        def interrupted(signum,frame):raise RuntimeError('Private prerequisite interrupted')
        signal.signal(signal.SIGTERM,interrupted)
        try:
            directory=run(cfg)
            result=json.loads((directory/'result.json').read_text())
            ordered=cfg.get('monado_window_order_probe',False)
            if result.get('result')!=('monado_window_order_prerequisite_only' if ordered else 'display_prerequisite_only') or result.get('cleanup_errors') or \
               result.get('game_launch_requested') is not False or result.get('monado_launch_requested') is not ordered:
                raise RuntimeError('Private prerequisite did not complete its owned extent')
        except BaseException as error:
            (output/'collection-outcome.json').write_text(json.dumps({'completed':False,'error':str(error)}))
            raise
        (output/'collection-outcome.json').write_text(json.dumps({'completed':True,'prerequisite_only':True,
            'private_run':str(directory),'collector_launched':False,'game_launched':False,
            'monado_launched':ordered,'data_ready_for_review':False}))
        return
    # Reuse the reviewed collector and run() cleanup. No second validation after
    # a standalone Wine invocation, no rewritten collection state machine.
    collector=cfg_path.parent/'collect.py'
    spec=importlib.util.spec_from_file_location('prepared_idle_collection',collector)
    module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module)
    sys.argv=[str(collector)]
    try:
        directory=Path(module.main()).resolve(strict=True)
        cfg=json.loads(cfg_path.read_text())
        if not directory.is_relative_to(Path(cfg['private_root']).resolve()/'runs'):
            raise RuntimeError('Collector returned a path outside its private run inventory')
        summary=json.loads((directory/'idle-collection-summary.json').read_text())
        if summary.get('data_ready_for_review') is not True:
            raise RuntimeError('Collection completed without the required both-eye replay/reference evidence')
    except BaseException as error:
        (output/'collection-outcome.json').write_text(json.dumps({'completed':False,'error':str(error)}))
        raise
    else:
        (output/'collection-outcome.json').write_text(json.dumps({'completed':True,'private_run':str(directory),
            'data_ready_for_review':True,'physical_grasp_verified':False,'native_release_verified':False}))


def launch(cfg_path, cfg, display_only=False, prerequisite_only=False):
    if not cfg.get('display_timing_probe'):raise RuntimeError('Private capture needs its D3D9 readiness prerequisite')
    if display_only and prerequisite_only:raise ValueError('Choose exactly one diagnostic extent')
    shell=selected_shell(cfg)
    base=cfg_path.parent;out=base/('display-check' if display_only else 'prerequisite-check' if prerequisite_only else 'private-display')
    out.mkdir(mode=0o700,exist_ok=False)
    token=secrets.token_hex(16)
    # Linux sockaddr_un is bounded by bytes, not characters. Nested fixture
    # paths can exceed it before any child/game starts. Keep the owned runtime
    # directly below the validated private root and fail before launch if long.
    runtime=Path(cfg['private_root']).resolve(strict=True)/('display-'+token)
    if len(os.fsencode(runtime/'ss2-vr-private'))>=108:
        raise RuntimeError('Private display socket path exceeds the native limit')
    runtime.mkdir(mode=0o700)
    env=private_environment(os.environ,runtime,token)
    # Exclusive reservation is consumed even on startup failure; never retry.
    with (base/('display-check-attempt.json' if display_only else 'prerequisite-attempt.json' if prerequisite_only else 'agent-capture-attempt.json')).open('x') as file:
        json.dump({'schema':1,'time_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
                   'source_products':cfg['expected_product_source'],'desktop_input':False,
                   'display_only':display_only,'prerequisite_only':prerequisite_only},file,indent=2)
    cmd=['weston','--backend=headless','--renderer=pixman','--shell='+shell,'--fake-seat',
         '--refresh-rate=60000','--width=1280','--height=720','--xwayland','--no-config',
         '--idle-time=0','--socket=ss2-vr-private','--log='+str(out/'weston.log'),
         '--',sys.executable,str(Path(__file__).resolve()),'--config',str(cfg_path),'--inside',str(out)]
    if display_only:cmd.append('--display-only')
    if prerequisite_only:cmd.append('--prerequisite-only')
    owned={};server=None;files=[];report={'schema':1,'desktop_input':False,'hardware_acceptance':False,
                                      'display_only':display_only,'prerequisite_only':prerequisite_only}
    def interrupted(signum,frame):raise RuntimeError('Private capture interrupted')
    previous={sig:signal.signal(sig,interrupted) for sig in (signal.SIGTERM,signal.SIGINT)}
    try:
        log=(out/'launch.log').open('xb');files.append(log)
        server=subprocess.Popen(cmd,env=env,stdout=log,stderr=subprocess.STDOUT,start_new_session=True)
        initial=identity(server.pid)
        # The child waits for this parent certificate before checking ownership.
        end=time.monotonic()+5
        while time.monotonic()<end:
            executed=identity(server.pid)
            if initial and executed and executed['start']==initial['start'] and \
               [part.decode() for part in executed['argv'] if part]==cmd:
                pending=out/'owner.pending'
                pending.write_text(json.dumps({'pid':executed['pid'],'start':executed['start'],'argv':cmd,'runtime':str(runtime)}))
                pending.rename(out/'owner.json')
                break
            if server.poll() is not None:raise RuntimeError('Private compositor failed before exec certification')
            time.sleep(.01)
        else:raise RuntimeError('Private compositor exec certification timed out')
        end=time.monotonic()+((cfg.get('timeout',60)+45 if cfg.get('monado_window_order_probe') else 75) if prerequisite_only else 285)
        while server.poll() is None:
            gather(owned,token,str(runtime),{os.getpid(),server.pid})
            if time.monotonic()>=end:raise TimeoutError('Private collection budget expired')
            time.sleep(.1)
        report['returncode']=server.returncode
        if server.returncode:raise RuntimeError('Private collection failed; preserve logs, do not repeat')
        # Weston exiting normally does not certify its application's success.
        outcome=json.loads((out/'collection-outcome.json').read_text())
        if outcome.get('completed') is not True or \
           (display_only and outcome.get('display_only') is not True) or \
           (prerequisite_only and outcome.get('prerequisite_only') is not True) or \
           (not display_only and not prerequisite_only and outcome.get('data_ready_for_review') is not True):
            reason=outcome.get('error')
            detail=(' '.join(reason.split())[:512] if isinstance(reason,str) and reason.strip() else
                    'required completion/readiness receipt is missing')
            raise RuntimeError('Collector did not complete: '+detail+'; preserve logs, do not repeat')
    except BaseException as error:
        report['error']=str(error)
        raise
    finally:
        errors=[];requests=[]
        def deferred(signum,frame):requests.append(signum)
        for sig in previous:signal.signal(sig,deferred)
        def safe(action):
            try:action()
            except BaseException as error:errors.append(str(error))
        try:
            safe(lambda:gather(owned,token,str(runtime),{os.getpid(),server.pid} if server else {os.getpid()}))
            # First request the Python collector's existing finally path.
            children=[p for p in owned.values() if str(Path(__file__).resolve()).encode() in p['argv']]
            for child in children:
                if still_owned(child):safe(lambda child=child:os.kill(child['pid'],signal.SIGTERM))
            grace=time.monotonic()+25
            while any(still_owned(p) for p in children) and time.monotonic()<grace:time.sleep(.1)
            deadline=time.monotonic()+15
            safe(lambda:gather(owned,token,str(runtime),{os.getpid(),server.pid} if server else {os.getpid()}))
            for item in list(owned.values()):safe(lambda item=item:stop_exact(item,deadline))
            if server and server.poll() is None:
                # Popen owns this unreaped child; never signal arbitrary Weston.
                safe(server.terminate)
                try:server.wait(timeout=3)
                except subprocess.TimeoutExpired:
                    safe(server.kill);safe(lambda:server.wait(timeout=2))
            safe(lambda:gather(owned,token,str(runtime),{os.getpid()}))
            for item in list(owned.values()):safe(lambda item=item:stop_exact(item,deadline))
            survivors=[{'pid':p['pid'],'start':p['start']} for p in owned.values() if still_owned(p)]
            if survivors:errors.append('Exact owned descendants survived cleanup')
            report.update(survivors=survivors,cleanup_errors=errors,deferred_signals=requests,
                          display_stopped=server is not None and server.poll() is not None)
            for file in files:safe(file.close)
            (out/'result.json').write_text(json.dumps(report,indent=2)+'\n')
        finally:
            for sig,handler in previous.items():signal.signal(sig,handler)
        if errors:raise RuntimeError('Private collection cleanup failed; inspect diagnostics')
        if requests:raise RuntimeError('Private collection interrupted during cleanup; diagnostics preserved')


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config',type=Path,required=True)
    modes=parser.add_mutually_exclusive_group()
    modes.add_argument('--run',action='store_true')
    modes.add_argument('--check',action='store_true')
    parser.add_argument('--inside',type=Path,help=argparse.SUPPRESS)
    modes.add_argument('--display-only',action='store_true',help='Run private X11 ownership preflight only; no Wine/game')
    modes.add_argument('--prerequisite-only',action='store_true',help='Run pinned D3D9 prerequisite; stop before Monado/SS2')
    args=parser.parse_args();cfg_path=args.config.resolve(strict=True)
    if args.inside and (args.run or args.check):parser.error('Internal display child cannot select public modes')
    if args.inside:
        end=time.monotonic()+5
        while not (args.inside/'owner.json').exists() and time.monotonic()<end:time.sleep(.01)
        inside(cfg_path,args.inside,args.display_only,args.prerequisite_only);return
    cfg=prepared_configuration(cfg_path)
    if args.prerequisite_only and cfg.get('display_prerequisite_only') is not True:
        parser.error('Prerequisite-only operation must be sealed in this configuration')
    if args.run and cfg.get('display_prerequisite_only') is True:
        parser.error('A prerequisite-only configuration cannot select game collection')
    if not cfg.get('display_timing_probe'):parser.error('Prepared private display requires the timing probe')
    if not args.run and not args.display_only and not args.prerequisite_only:
        print('Prepared private display configuration verified; no process launched.');return
    os.nice(10)
    launch(cfg_path,cfg,args.display_only,args.prerequisite_only)

if __name__=='__main__':main()
