#!/usr/bin/env python3
"""Prepared neutral collection on a separate headless Weston/Xwayland display.

Default/--check performs source/config checks only. --run consumes one attempt.
No game assets or settings are generated by this launcher. Use a sealed lab.
"""
import argparse
import datetime
import importlib.util
import json
import os
from pathlib import Path
import secrets
import signal
import subprocess
import sys
import time
from runtime_lab import identity, still_owned, stop_exact, validate, checked_file

def prepared_configuration(path):
    if path.name!='config.json':raise ValueError('Collector must use its sealed config.json')
    cfg=json.loads(path.read_text());validate(cfg)
    if cfg.get('idle_weapon_probe') is not True or not cfg.get('display_timing_probe'):
        raise ValueError('Prepared private display requires the neutral collector and timing probe')
    receipt=json.loads(Path(cfg['idle_preparation']['path']).read_text())
    checked_file(path.parent/'collect.py',receipt['private_wrapper_sha256'])
    return cfg


def private_environment(original, runtime, token):
    env=original.copy()
    for name in ('DISPLAY','WAYLAND_DISPLAY','XAUTHORITY','DBUS_SESSION_BUS_ADDRESS','MIR_SOCKET'):
        env.pop(name,None)
    env.update(XDG_RUNTIME_DIR=str(runtime),SS2VR_LAB_DISPLAY_ROOT=str(runtime),
               SS2VR_PRIVATE_CAPTURE_TOKEN=token,SS2VR_LAB_PRIVATE_DISPLAY='1',PYTHONDONTWRITEBYTECODE='1')
    return env


def tagged(raw, token, root):
    rows=raw.split(b'\0')
    return all([row for row in rows if row.startswith((key+'=').encode())]==[(key+'='+value).encode()]
               for key,value in (('SS2VR_PRIVATE_CAPTURE_TOKEN',token),('SS2VR_LAB_DISPLAY_ROOT',root)))


def gather(owned, token, root, exclude):
    for proc in Path('/proc').iterdir():
        if not proc.name.isdigit() or int(proc.name) in exclude:continue
        item=identity(proc.name)
        if not item:continue
        try:raw=(proc/'environ').read_bytes()
        except OSError:continue
        if tagged(raw,token,root):owned[(item['pid'],item['start'])]=item


def inside(cfg_path, output):
    # Weston executes this child only after its private display is ready. Certify
    # the exact parent incarnation and actual executed argv, not Popen's fork.
    expected=json.loads((output/'owner.json').read_text())
    parent=identity(os.getppid())
    if not parent or parent['pid']!=expected['pid'] or parent['start']!=expected['start'] or \
       [part.decode() for part in parent['argv'] if part]!=expected['argv']:
        raise RuntimeError('Private compositor parent identity differs')
    root=str(output/'runtime')
    if os.environ.get('XDG_RUNTIME_DIR')!=root or os.environ.get('SS2VR_LAB_DISPLAY_ROOT')!=root or \
       os.environ.get('WAYLAND_DISPLAY')!='ss2-vr-private' or not os.environ.get('DISPLAY','').startswith(':'):
        raise RuntimeError('Private display environment differs; no desktop fallback')
    servers=[identity(p.name) for p in Path('/proc').iterdir() if p.name.isdigit()]
    servers=[p for p in servers if p and p['parent']==parent['pid'] and p['name']=='Xwayland'
             and os.environ['DISPLAY'].encode() in p['argv']]
    if len(servers)!=1:raise RuntimeError('Private Xwayland ownership is ambiguous')
    # The runtime lab changes XDG_RUNTIME_DIR for Monado. Force X11, rather than
    # leaving a Wayland selector pointing at the old runtime directory.
    os.environ.pop('WAYLAND_DISPLAY',None)
    os.environ.pop('XAUTHORITY',None)
    check=subprocess.run(['xrandr','--current'],capture_output=True,timeout=5)
    (output/'xrandr.txt').write_bytes(check.stdout+check.stderr)
    if check.returncode:raise RuntimeError('Private display current-mode query failed')
    (output/'child.json').write_text(json.dumps({'pid':os.getpid(),'start':identity(os.getpid())['start'],
        'display':os.environ['DISPLAY'],'xwayland_pid':servers[0]['pid'],'xwayland_start':servers[0]['start'],
        'desktop_input':False},indent=2)+'\n')
    # Reuse the reviewed collector and run() cleanup. No second validation after
    # a standalone Wine invocation, no rewritten collection state machine.
    collector=cfg_path.parent/'collect.py'
    spec=importlib.util.spec_from_file_location('prepared_idle_collection',collector)
    module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module)
    sys.argv=[str(collector)]
    try:
        directory=Path(module.main()).resolve(strict=True)
        cfg=json.loads(cfg_path.read_text())
        if not directory.is_relative_to(Path(cfg['private_root']).resolve()/'runs'):
            raise RuntimeError('Collector returned a path outside its private run inventory')
        summary=json.loads((directory/'idle-collection-summary.json').read_text())
        if summary.get('data_ready_for_review') is not True:
            raise RuntimeError('Collection completed without the required both-eye replay/reference evidence')
    except BaseException as error:
        (output/'collection-outcome.json').write_text(json.dumps({'completed':False,'error':str(error)}))
        raise
    else:
        (output/'collection-outcome.json').write_text(json.dumps({'completed':True,'private_run':str(directory),
            'data_ready_for_review':True,'physical_grasp_verified':False,'native_release_verified':False}))


def launch(cfg_path, cfg):
    if not cfg.get('display_timing_probe'):raise RuntimeError('Private capture needs its D3D9 readiness prerequisite')
    base=cfg_path.parent;out=base/'private-display'
    out.mkdir(mode=0o700,exist_ok=False)
    runtime=out/'runtime';runtime.mkdir(mode=0o700)
    token=secrets.token_hex(16);env=private_environment(os.environ,runtime,token)
    # Exclusive reservation is consumed even on startup failure; never retry.
    with (base/'agent-capture-attempt.json').open('x') as file:
        json.dump({'schema':1,'time_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
                   'source_products':cfg['expected_product_source'],'desktop_input':False},file,indent=2)
    cmd=['weston','--backend=headless','--renderer=pixman','--shell=kiosk','--fake-seat',
         '--refresh-rate=60000','--width=1280','--height=720','--xwayland','--no-config',
         '--idle-time=0','--socket=ss2-vr-private','--log='+str(out/'weston.log'),
         '--',sys.executable,str(Path(__file__).resolve()),'--config',str(cfg_path),'--inside',str(out)]
    owned={};server=None;files=[];report={'schema':1,'desktop_input':False,'hardware_acceptance':False}
    def interrupted(signum,frame):raise RuntimeError('Private capture interrupted')
    previous={sig:signal.signal(sig,interrupted) for sig in (signal.SIGTERM,signal.SIGINT)}
    try:
        log=(out/'launch.log').open('xb');files.append(log)
        server=subprocess.Popen(cmd,env=env,stdout=log,stderr=subprocess.STDOUT,start_new_session=True)
        initial=identity(server.pid)
        # The child waits for this parent certificate before checking ownership.
        end=time.monotonic()+5
        while time.monotonic()<end:
            executed=identity(server.pid)
            if initial and executed and executed['start']==initial['start'] and \
               [part.decode() for part in executed['argv'] if part]==cmd:
                pending=out/'owner.pending'
                pending.write_text(json.dumps({'pid':executed['pid'],'start':executed['start'],'argv':cmd}))
                pending.rename(out/'owner.json')
                break
            if server.poll() is not None:raise RuntimeError('Private compositor failed before exec certification')
            time.sleep(.01)
        else:raise RuntimeError('Private compositor exec certification timed out')
        end=time.monotonic()+285
        while server.poll() is None:
            gather(owned,token,str(runtime),{os.getpid(),server.pid})
            if time.monotonic()>=end:raise TimeoutError('Private collection budget expired')
            time.sleep(.1)
        report['returncode']=server.returncode
        if server.returncode:raise RuntimeError('Private collection failed; preserve logs, do not repeat')
        # Weston exiting normally does not certify its application's success.
        outcome=json.loads((out/'collection-outcome.json').read_text())
        if outcome.get('completed') is not True or outcome.get('data_ready_for_review') is not True:
            raise RuntimeError('Collector did not complete; preserve logs, do not repeat')
    except BaseException as error:
        report['error']=str(error)
        raise
    finally:
        errors=[];requests=[]
        def deferred(signum,frame):requests.append(signum)
        for sig in previous:signal.signal(sig,deferred)
        def safe(action):
            try:action()
            except BaseException as error:errors.append(str(error))
        try:
            safe(lambda:gather(owned,token,str(runtime),{os.getpid(),server.pid} if server else {os.getpid()}))
            # First request the Python collector's existing finally path.
            children=[p for p in owned.values() if str(Path(__file__).resolve()).encode() in p['argv']]
            for child in children:
                if still_owned(child):safe(lambda child=child:os.kill(child['pid'],signal.SIGTERM))
            grace=time.monotonic()+25
            while any(still_owned(p) for p in children) and time.monotonic()<grace:time.sleep(.1)
            deadline=time.monotonic()+15
            safe(lambda:gather(owned,token,str(runtime),{os.getpid(),server.pid} if server else {os.getpid()}))
            for item in list(owned.values()):safe(lambda item=item:stop_exact(item,deadline))
            if server and server.poll() is None:
                # Popen owns this unreaped child; never signal arbitrary Weston.
                safe(server.terminate)
                try:server.wait(timeout=3)
                except subprocess.TimeoutExpired:
                    safe(server.kill);safe(lambda:server.wait(timeout=2))
            safe(lambda:gather(owned,token,str(runtime),{os.getpid()}))
            for item in list(owned.values()):safe(lambda item=item:stop_exact(item,deadline))
            survivors=[{'pid':p['pid'],'start':p['start']} for p in owned.values() if still_owned(p)]
            if survivors:errors.append('Exact owned descendants survived cleanup')
            report.update(survivors=survivors,cleanup_errors=errors,deferred_signals=requests,
                          display_stopped=server is not None and server.poll() is not None)
            for file in files:safe(file.close)
            (out/'result.json').write_text(json.dumps(report,indent=2)+'\n')
        finally:
            for sig,handler in previous.items():signal.signal(sig,handler)
        if errors:raise RuntimeError('Private collection cleanup failed; inspect diagnostics')
        if requests:raise RuntimeError('Private collection interrupted during cleanup; diagnostics preserved')


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--config',type=Path,required=True)
    parser.add_argument('--run',action='store_true')
    parser.add_argument('--check',action='store_true')
    parser.add_argument('--inside',type=Path,help=argparse.SUPPRESS)
    args=parser.parse_args();cfg_path=args.config.resolve(strict=True)
    if args.inside:
        end=time.monotonic()+5
        while not (args.inside/'owner.json').exists() and time.monotonic()<end:time.sleep(.01)
        inside(cfg_path,args.inside);return
    cfg=prepared_configuration(cfg_path)
    if args.run and args.check:parser.error('Choose --run or --check')
    if not cfg.get('display_timing_probe'):parser.error('Prepared private display requires the timing probe')
    if not args.run:
        print('Prepared private display configuration verified; no process launched.');return
    os.nice(10)
    launch(cfg_path,cfg)

if __name__=='__main__':main()
